/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface Listing {
  'id' : bigint,
  'title' : string,
  'description' : string,
  'category' : string,
  'price' : string,
  'techTags' : Array<string>,
  'status' : string,
  'featured' : boolean,
}
export interface ServicePackage {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'price' : string,
  'features' : Array<string>,
  'popular' : boolean,
}
export interface Inquiry {
  'id' : bigint,
  'caller' : Principal,
  'clientName' : string,
  'email' : string,
  'phone' : string,
  'message' : string,
  'serviceType' : string,
  'status' : string,
  'notes' : string,
  'timestamp' : bigint,
}
export interface UserActivity {
  'id' : bigint,
  'principal' : Principal,
  'principalText' : string,
  'action' : string,
  'detail' : string,
  'timestamp' : bigint,
}
export interface SearchTermCount {
  'term' : string,
  'count' : bigint,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'getListings' : ActorMethod<[], Array<Listing>>,
  'addListing' : ActorMethod<[Listing], bigint>,
  'updateListing' : ActorMethod<[Listing], boolean>,
  'deleteListing' : ActorMethod<[bigint], boolean>,
  'getPackages' : ActorMethod<[], Array<ServicePackage>>,
  'updatePackage' : ActorMethod<[ServicePackage], boolean>,
  'submitInquiry' : ActorMethod<[string, string, string, string, string], bigint>,
  'getMyInquiries' : ActorMethod<[], Array<Inquiry>>,
  'getAllInquiries' : ActorMethod<[], Array<Inquiry>>,
  'updateInquiryStatus' : ActorMethod<[bigint, string, string], boolean>,
  'getInsights' : ActorMethod<[], [bigint, bigint, bigint, bigint]>,
  'logActivity' : ActorMethod<[string, string], undefined>,
  'getActivityLog' : ActorMethod<[], Array<UserActivity>>,
  'getSearchTerms' : ActorMethod<[], Array<SearchTermCount>>,
  'askAgent' : ActorMethod<[string], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
